openapi: 3.0.1
info:
    title: 辅助设计面板
    description: 辅助设计面板
    version: "v1.0.1"
servers:
    - url: http://127.0.0.1:8082
paths:
    /output/Writeline:
        post:
            operationId: outputWriteline
            summary: 输出日志
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/outputWriteline"
            responses:
                "200":
                    description: 输出日志成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"

components:
    schemas:
        outputWriteline:
            type: object
            required: [msg]
            properties:
                msg:
                    type: string
                    description: 消息
        messageResponse:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 回复信息